### ISSUE TITLE
Unable to find chromedriver

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [heroku/heroku-buildpack-chromedriver#1]
I obtain this error;
`Selenium::WebDriver::Error::WebDriverError -  Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.`

I suspect I need to setup the correct path as an environment variable.

**Comment by joshwlewis** [comment]
Hi Arnold -- Are you using this for a Heroku CI run or a normal build?

**Comment by arnoldtonderaimarunda** [comment]
@joshwlewis, thanks for your response. Its for a normal build

**Comment by joshwlewis** [comment]
@arnoldmarunda, #2 should fix this. Can you give it a try by using `https://github.com/heroku/heroku-buildpack-chromedriver#use-app-path` as your buildpack and see if it works?

**Comment by arnoldtonderaimarunda** [comment]
@joshwlewis Now get the error
`Selenium::WebDriver::Error::UnknownError - unknown error: cannot find Chrome binary`
Seems to have broken the Chrome buildpack path, unless I have done something wrong.
Please advise

**Comment by joshwlewis** [comment]
Hi @arnoldmarunda -- It looks like you aren't telling chromedriver where to find chrome. There's a section on how to do that here: https://github.com/heroku/heroku-buildpack-google-chrome#selenium.

**Comment by arnoldtonderaimarunda** [comment]
Noted. Thank you
