### ISSUE TITLE
chromedriver unable to locate element

### ISSUE THREAD

**Issue by pyronlaboratory** [heroku/heroku-buildpack-chromedriver#18]
I've deployed a selenium script using python with chromedriver in play on my heroku server.

The driver is configured properly, and it does launch an instance. However, the driver is unable to locate the elements.

The script is working fine when tested on local server.

Any idea what could have gone wrong here?

**Comment by pyronlaboratory** [comment]
Nevermind, I got it!

**Comment by EArminjon** [comment]
same issue, how did you fix it ?

**Comment by pyronlaboratory** [comment]
I did it few months back, so I don't exactly remember, but keep tweaking with the browser/driver object's configurations. It'll get you going. I've been using geckodriver though for my projects nowadays (https://pyronlaboratory.github.io/heroku-integrated-firefox-geckodriver/).

**Comment by EArminjon** [comment]
I follow your like, i switch from chrome to firefox but it still not work on Heroku.
My code work with Firefox or Chrome on my pc :'(

```bash
SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

```node
const {Builder, By, until} = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');

const screen = {
  width: 1920,
  height: 1080
};

let options = new firefox.Options();
//Below arguments are critical for Heroku deployment
options.addArguments("--headless");
options.addArguments("--disable-gpu");
options.addArguments("--no-sandbox");
options.windowSize(screen);


let driver = new Builder()
  .forBrowser('firefox')
  .setFirefoxOptions(options)
  .build();
```

![Sans titre](https://user-images.githubusercontent.com/37028599/72630817-6ce16100-3953-11ea-8137-f554038a67c2.png)

**Comment by pyronlaboratory** [comment]
This thread is closed and might confuse the future readers, since we're discussing about `heroku-integrated-firefox-geckodriver` and **NOT** `heroku-buildpack-chromedriver`.

I would suggest you to create/open a new issue [here](https://github.com/pyronlaboratory/heroku-integrated-firefox-geckodriver/issues) to continue the discussion.
