### ISSUE TITLE
no documentation?

### ISSUE THREAD

**Issue by estani** [heroku/heroku-buildpack-chromedriver#22]
Should this still work? It's not deprecated, but there's no info regarding where the chromedriver is located...
Why not use an ENV variable like https://github.com/heroku/heroku-buildpack-google-chrome and document it as such?

Apparently it ends up in `/app/.chromedriver/bin/chromedriver` but it would be nice to have the proper documentation instead of guessing it.

**Comment by edmorley** [comment]
This buildpack has since been replaced by a new combined Chrome+chromedriver buildpack that resolves a number of issues:
https://github.com/heroku/heroku-buildpack-chrome-for-testing

As such this buildpack is being sunset.
