### ISSUE TITLE
unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by mattblank11** [heroku/heroku-buildpack-chromedriver#24]
Hey all!

Have been using the Chrome + ChromeDriver Buildpacks for a couple years for a Python script that I run each day. I pushed a new commit that **did not** impact my webdriver code and received the following error when my script ran:

```
File "update_data.py", line 111, in download
    zenplanner(client_dict, download_dates, driver)
  File "/app/download_methods.py", line 384, in zenplanner
    driver.get(zenplanner_urls[report])
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=83.0.4103.116)
```

As a follow up, the exact same code works normally on my local machine. I only receive this error when the script runs through Heroku.

I'd appreciate any guidance you all can provide to resolve this issue!

Thanks,
Matt

**Comment by MarkBone** [comment]
did you solve it? Please help me

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
