### ISSUE TITLE
Wrong version is downloaded

### ISSUE THREAD

**Issue by vaknin** [heroku/heroku-buildpack-chromedriver#26]
I understand that you're pulling the chromedriver's stable version from [this page](https://chromedriver.storage.googleapis.com/LATEST_RELEASE).
However, it is not the **actual** stable release, as can be seen [here](https://chromedriver.chromium.org/).
The first link shows that stable is v85 (which is beta, actually), and the 2nd link shows stable is v84.

**Comment by i386** [comment]
The issue is with `heroku-chrome-buildpack` installing `chromium-chomedriver` https://github.com/heroku/heroku-buildpack-google-chrome/issues/94

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
