### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 85

### ISSUE THREAD

**Issue by Steven4294** [heroku/heroku-buildpack-chromedriver#27]
```Message: session not created: This version of ChromeDriver only supports Chrome version 85```

Getting an error on a cronjob i had running for the past several months today. I think the driver needs to be updated to support the latest version of chrome.

**Comment by weinbergdavid** [comment]
I have the same error. Any advice?

**Comment by sixro** [comment]
Do you still have this error?  
I don't have it in my logs and I didn't set a `CHROME_VERSION`...

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
