### ISSUE TITLE
Errors on Heroku R14 etc...

### ISSUE THREAD

**Issue by sixro** [heroku/heroku-buildpack-chromedriver#31]
Hi, I am not sure this is considered good...  
I posted a [question on StackOverflow](https://stackoverflow.com/questions/68004136/how-to-avoid-process-running-mem-544m100-3-on-heroku-with-selenium) that no one seems able to answer.  
With this issue I am trying to collect more knowledge to understand best practices and to avoid errors.  

I suppose that you are using `chromedriver` on `heroku` in some of your applications.  
I would like to know if you consider **true** the following statements:
  * When using `selenium` with `chromedriver`, you have call everytime `WebDriver.quit` even if in your scraping you have to login everytime you do something
  * You can't have a pool of already created `chromedriver`(s) to avoid the creation time of them, unless you have a paid plan with `heroku` giving more than 512MB
  * You can't create a `WebDriver` and closing it after a number of usages, because anyway after some `navigate().to(URL)` it will fail due to max memory reached. This is not related to window handles opened, because checking constantly I have only 1 window handle

Thanks in advance for your answers

**Comment by jstoxrocky** [comment]
@sixro Sorry for the ping on a 2 year old post but running into the same memory related issues. Do you have any advice here 2 years later? I would appreciate any guidance!

**Comment by sixro** [comment]
Hi @jstoxrocky, unfortunately no.
If I remember correctly I had to restart from time to time everything.

**Comment by jstoxrocky** [comment]
Got it -thanks

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
