### ISSUE TITLE
Push rejected, failed to compile chromedriver app.

### ISSUE THREAD

**Issue by jalunceford** [heroku/heroku-buildpack-chromedriver#33]
I'm trying to push the changes for my app to Heroku, and for some reason I am getting the following error when I try to push:

 "Archive:  /tmp/chromedriver.zip
remote:   End-of-central-directory signature not found.  Either this file is not
remote:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
remote:   latter case the central directory and zipfile comment will be found on
remote:   the last disk(s) of this archive.
remote: unzip:  cannot find zipfile directory in one of /tmp/chromedriver.zip or
remote:         /tmp/chromedriver.zip.zip, and cannot find /tmp/chromedriver.zip.ZIP, period.
remote:  !     Push rejected, failed to compile chromedriver app."

The buildpacks I am using are heroku/python, https://github.com/heroku/heroku-buildpack-google-chrome, and https://github.com/heroku/heroku-buildpack-chromedriver. I am using the Selenium ChromeDriver in my app. My app is running on one worker dyno. Any ideas? Thanks!

**Comment by nphenley** [comment]
Hey did you ever figure this out?

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
