### ISSUE TITLE
Chrome driver Message: session not created: This version of ChromeDriver only supports Chrome version 93

### ISSUE THREAD

**Issue by FERDIZ-afk** [heroku/heroku-buildpack-chromedriver#35]
![IMG_20210729_222016](https://user-images.githubusercontent.com/69185890/127519317-342bd0fc-1c22-41ed-a591-e90f5eafcde1.jpg)

Message: session not created: This version of ChromeDriver only supports Chrome version 93

Current browser version is 92.0.4515.107 with binary path /app/.apt/opt/google/chrome/chrome

set version chrome driver 

heroku config:set CHROMEDRIVER_VERSION=version number  --app

![IMG_20210802_072639](https://user-images.githubusercontent.com/69185890/127790221-00f481d4-aafe-403e-b9f2-d66f8e2d839b.jpg)

**Comment by FERDIZ-afk** [comment]
> ![IMG_20210729_222016](https://user-images.githubusercontent.com/69185890/127519317-342bd0fc-1c22-41ed-a591-e90f5eafcde1.jpg)
> 
> Message: session not created: This version of ChromeDriver only supports Chrome version 93
> 
> Current browser version is 92.0.4515.107 with binary path /app/.apt/opt/google/chrome/chrome
> 
> Plis help me

**Comment by hemanth-kotagiri** [comment]
Hi, @FERDIZ-afk. I had the same issue. I just added a Configuration Variable as such:
`CHROMEDRIVER_VERSION : 91.0.4472.101`

In my case, the version of the browser that was installed was 91, but the chrome driver that was being downloaded was 92. So there was a conflict. In your case, you'd need to pick the one among V92 drivers from here: [Chrome WebDriver](https://chromedriver.chromium.org/downloads)

and then, just add the configuration variable as I did with the version you choose. And you should be good to go.

**Comment by FERDIZ-afk** [comment]
Hello too @hemanth-kotagiri Do you run it on heroku

**Comment by hemanth-kotagiri** [comment]
Hey there, @FERDIZ-afk. Yes, I do. Were you able to resolve your issue?

**Comment by FERDIZ-afk** [comment]
I have solved the problem

**Comment by dante-lafranchi** [comment]
@FERDIZ-afk I'm having the same issue but adding the CHROMEDRIVER_VERSION config var isn't working for me. Did you do something else too? Thanks

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
