### ISSUE TITLE
chromedriver version not match with browser

### ISSUE THREAD

**Issue by foremtehan** [heroku/heroku-buildpack-chromedriver#39]
My app crashed today with the following error:

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 104
2022-08-04T11:05:59.494339+00:00 app[worker.1]: Current browser version is 103.0.5060.134 with binary path /app/.apt/usr/bin/google-chrome
```

I set the env variable `CHROMEDRIVER_VERSION` to (and re-deploy the app)
103.0.5060.134
or
104.0.5112.79

But both of them has same error, What should i do now ? We have crash every season ?

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
