### ISSUE TITLE
Doesn't create an export file

### ISSUE THREAD

**Issue by mcolyer** [heroku/heroku-buildpack-chromedriver#4]
As part of the buildpack [API for composing multiple buildpacks](https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks) the build process expects an `export` file to exist and if it doesn't it throws an error in the build log.

Would it be possible to place an empty export file to quiet the build logs?

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
