### ISSUE TITLE
From chrome 115 the location of the download is changed

### ISSUE THREAD

**Issue by isparks** [heroku/heroku-buildpack-chromedriver#42]
It is now (for example):

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.98/linux64/chromedriver-linux64.zip

And exactly matches the version number of chrome so could be auto-detected. See:

https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE

**Comment by edmorley** [comment]
Fixed by #51 + #52.
