### ISSUE TITLE
curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by pboese** [heroku/heroku-buildpack-chromedriver#58]
Heya, when deploying I get the following error

```
remote: -----> chromedriver app detected
remote: -----> Using chromedriver v93.0.4577.63 (set by the env var 'CHROMEDRIVER_VERSION')...
remote: -----> Downloading chromedriver v93.0.4577.63...
remote: curl: (22) The requested URL returned error: 404
remote:  !     Push rejected, failed to compile chromedriver app.
remote:
remote:  !     Push failed
```

It seems the URL used to fetch the chromedriver is not working:

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/93.0.4577.63/linux64/chromedriver-linux64.zip

I tried other versions (we always get the version string from https://chromedriver.storage.googleapis.com/index.html) but they don't work either. 

I added a PR to fix the issue.

**Comment by pboese** [comment]
I forked the repository, this fix should do

https://github.com/pboese/heroku-buildpack-chromedriver/blob/main/bin/compile#L39

Sorry, I don't know how to create a proper pull request :-(

**Comment by rajinsyed** [comment]
Same issue. Any solutions?

**Comment by edmorley** [comment]
Older versions of chromedriver are no longer supported by the latest version of this buildpack.

See here for your options:
https://github.com/heroku/heroku-buildpack-chromedriver/issues/55#issuecomment-1686212805

**Comment by weshatheleopard** [comment]
Well, SOME people may need to pin to an older version, but WE need to pin to a newer version, that doesn't exist at the old URL. I know we can fork (and we **will**), but the solution you offer is a non-solution. The code can check BOTH URLs, and pick one of the two where the requested version exists.

**Comment by edmorley** [comment]
@weshatheleopard Pinning to a newer version still works, and is unrelated to this thread. Use the latest version of the buildpack (either unpinned, or pinned to the latest buildpack SHA), and then set `CHROMEDRIVER_VERSION` to the new Chromdriver version you want to use.

**Comment by edmorley** [comment]
And I agree one could design a solution that adjusts the URL based on version (after some discovery about what versions exist at what URLs). This buildpack isn't officially supported and is provided as best-effort - so someone from the community would need to implement such a solution - PRs welcome :-)

**Comment by edmorley** [comment]
This buildpack has since been replaced by a new combined Chrome+chromedriver buildpack that resolves a number of issues:
https://github.com/heroku/heroku-buildpack-chrome-for-testing

As such this buildpack is being sunset - please switch to the new buildpack.
