### ISSUE TITLE
CHROMEDRIVER_VERSION being ignored on Heroku

### ISSUE THREAD

**Issue by robertr2112** [heroku/heroku-buildpack-chromedriver#60]
I am using Selenium with Chromedriver and Chrome to scrape data from a website. I've started getting the following error:

    from session not created: This version of ChromeDriver only supports Chrome version 118
    Current browser version is 117.0.5938.132

But I have CHROMEDRIVER_VERSION set as follows:

    === fbpmp Config Vars
    CHROMEDRIVER_VERSION:       117.0.5938.132
From everything I could find this appears to be the proper way to lock down the version of the chromedriver buildpack. What am I doing wrong that is causing this to fail?

This is the last build log from 9/28:

    -----> chromedriver app detected
    -----> Using chromedriver v117.0.5938.132 (set by the env var 'CHROMEDRIVER_VERSION')...
    -----> Downloading chromedriver v117.0.5938.132...
    Archive:  /tmp/chromedriver.zip
      inflating: /tmp/build_7275b69c/.chromedriver/bin/LICENSE.chromedriver  
      inflating: /tmp/build_7275b69c/.chromedriver/bin/chromedriver  
    -----> Creating chromedriver export scripts...

**Comment by mars** [comment]
The problem is that newer Chrome versions are being downloaded, but Chromedriver is not in sync.

We recently discovered this problem, and are looking into solving it using the official [Chrome for Testing setup](https://chromedriver.chromium.org/downloads/version-selection). Will probably require making a new buildpack, for this new strategy.

**Comment by robertr2112** [comment]
Is there a timeframe for when the new buildpack, or a fix to the current one, will be released?--Bob's iPhoneOn Dec 6, 2023, at 4:53 PM, Mars Hall ***@***.***> wrote:﻿
The problem is that newer Chrome versions are being downloaded, but Chromedriver is not in sync.
We recently discovered this problem, and are looking into solving it using the official Chrome for Testing setup. Will probably require making a new buildpack, for this new strategy.

**Comment by naoyanickf** [comment]
@mars I also wait new buildpack!

**Comment by naoyanickf** [comment]
@robertr2112 I'm deploying with a temporary solution. if you need, i will tell you. it's not smart way...

**Comment by robertr2112** [comment]
Sure, I'd love to hear your solution.


------ Original Message ------
From "Naoya Fujita" ***@***.***>
To "heroku/heroku-buildpack-chromedriver" 
***@***.***>
Cc "robertr2112" ***@***.***>; "Mention" 
***@***.***>
Date 12/19/2023 8:54:25 PM
Subject Re: [heroku/heroku-buildpack-chromedriver] CHROMEDRIVER_VERSION 
being ignored on Heroku (Issue #60)

**Comment by naoyanickf** [comment]
@robertr2112 To use old version chrome and chrome binary,  

i fork this repo and host https://github.com/naoyanickf/heroku-buildpack-chromedriver
this is 1 year old version of this repo.

if you switch your build pack url to my one, you can specify old version chrome and chrome driver version like 110.0.5481.77

<img width="880" alt="スクリーンショット 2023-12-20 12 39 16" src="https://github.com/heroku/heroku-buildpack-chromedriver/assets/5179467/7ec93fd6-f01f-486a-a4e2-a1ec6a1a6ed3">

<img width="845" alt="スクリーンショット 2023-12-20 12 38 22" src="https://github.com/heroku/heroku-buildpack-chromedriver/assets/5179467/2c0c2e4e-da46-492e-86f3-12af5e719f94">

**Comment by robertr2112** [comment]
Ok. Thank you for the information!--Bob's iPhoneOn Dec 19, 2023, at 9:39 PM, Naoya Fujita ***@***.***> wrote:﻿
@robertr2112 To use old version chrome and chrome binary,
i fork this repo and host https://github.com/naoyanickf/heroku-buildpack-chromedriver
this is 1 year old version of this repo.
if you switch your build pack url to my one, you can specify old version chrome and chrome driver version like 110.0.5481.77
2023-12-20.12.39.16.png (view on web)
2023-12-20.12.38.22.png (view on web)

**Comment by edmorley** [comment]
This buildpack has since been replaced by a new combined Chrome+chromedriver buildpack that resolves a number of issues (including this one):
https://github.com/heroku/heroku-buildpack-chrome-for-testing

As such this buildpack is being sunset - please switch to the new buildpack.
