### ISSUE TITLE
Unable to download Chromedriver v121.0.6167.184

### ISSUE THREAD

**Issue by aveedibya** [heroku/heroku-buildpack-chromedriver#63]
Chromedriver URL returns 404. Unable to download from: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip

<img width="1276" alt="image" src="https://github.com/heroku/heroku-buildpack-chromedriver/assets/5461802/16e597c1-0692-4d8e-ae45-cf533a1cefa2">

**Comment by bkbirr** [comment]
I am receiving the same error starting 25 minutes ago.

**Comment by akodkod** [comment]
+1 for this issue

**Comment by bkbirr** [comment]
Looks like google changed the url. 

ZIP_URL should be changed from:
ZIP_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$VERSION/linux64/chromedriver-linux64.zip"
to
 ZIP_URL="https://storage.googleapis.com/chrome-for-testing-public/$VERSION/linux64/chromedriver-linux64.zip"

I can submit a PR tonight if needed.

**Comment by mars** [comment]
This fix has been released.

**Comment by aveedibya** [comment]
Thanks for resolving this so quickly!
