### ISSUE TITLE
Explicitly set Version to ensure Deployment Repeatability

### ISSUE THREAD

**Issue by laverick** [heroku/heroku-buildpack-chromedriver#8]
The way I understand this, tracking the latest chromedriver release and not letting developers explicitly set it (e.g. via environment variable) means deploying a certain commit to a certain environment does not guarantee the same result. An update on Google's end could break my app's functionality on a new deploy and without the ability to specify a version there would be no way for me to recover the old working setup.

This is the corollary of the following issue, which has some additional detail:
https://github.com/heroku/heroku-buildpack-google-chrome/issues/48

**Comment by bigkevmcd** [comment]
I've landed a change #9 which at least allows configuration of the chromedriver binary.
